services:
  dev:
    container_name: zoomsdk-build
    build: ./
    platform: linux/amd64
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
    ports:
      - 2222:22
    cap_add:
      - sys_ptrace